language: cpp
os:
  - linux
  - osx
dist: trusty
osx_image: xcode7.3
sudo: required

before_install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then . .travis.linux; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then . .travis.osx; fi

before_script:
  - mkdir src/build
  - cd src/build
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-8.0 ..; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then CC=/usr/local/opt/llvm/bin/clang CXX=/usr/local/opt/llvm/bin/clang++ LDFLAGS=-L/usr/local/opt/llvm/lib/ cmake -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" ..; fi

script:
  - make -j2 VERBOSE=1

notifications:
  email: false
